# Generated by Django 4.2.10 on 2024-02-25 03:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_clinicalsite_protocol_alter_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.AddField(
            model_name='protocol',
            name='clinical_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='survey.clinicalsite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='survey.protocol'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='study_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('clinical_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='survey.clinicalsite')),
                ('protocols', models.ManyToManyField(blank=True, related_name='participants', to='survey.protocol')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='survey.participant'),
        ),
    ]
