# Generated by Django 4.2.10 on 2024-03-14 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0018_surveyy_questionsurvey_choicess"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choicess",
            new_name="Redirection",
        ),
    ]
