# Generated by Django 4.2.11 on 2024-03-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_rename_choicess_redirection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocol',
            old_name='end_date',
            new_name='actual_end_date',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='start_date',
            new_name='protocol_start_date',
        ),
        migrations.AddField(
            model_name='protocol',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
