# Generated by Django 4.2.11 on 2024-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_rename_end_date_protocol_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'ongoing')], default='Unknown', max_length=20),
        ),
    ]
