# Generated by Django 4.2.11 on 2024-03-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_protocol_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='enrollment_status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Screened', 'Screened'), ('Excluded', 'Excluded')], default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='status',
            field=models.CharField(choices=[('Unknown ', 'Unknown'), ('Completed', 'Completed'), ('Ongoing', 'ongoing')], default='Unknown', max_length=20),
        ),
    ]
