# Generated by Django 4.2.11 on 2024-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_participant_enrollment_status_alter_protocol_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='exlusion_reason',
            field=models.CharField(choices=[('Unknown', '-------'), ('Withdrawn Consent', 'Withdrawn'), ('Ineligible', 'Ineligible'), ('Other', 'Other')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='screening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='enrollment_status',
            field=models.CharField(choices=[('Unknown', '-------'), ('Enrolled', 'Enrolled'), ('Screened', 'Screened'), ('Excluded', 'Excluded')], default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='status',
            field=models.CharField(choices=[('Unknown', '-------'), ('Completed', 'Completed'), ('Ongoing', 'ongoing')], default='Unknown', max_length=20),
        ),
    ]
