# Generated by Django 4.2.11 on 2024-03-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0025_medicationrecord_medications_delete_surveyy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="exlusion_reason",
        ),
        migrations.AddField(
            model_name="participant",
            name="exclusion_reason",
            field=models.CharField(
                choices=[
                    ("Withdrawn Consent", "Withdrawn"),
                    ("Ineligible", "Ineligible"),
                    ("Other", "Other"),
                ],
                default="Unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("Enrolled", "Enrolled"),
                    ("Screened", "Screened"),
                    ("Excluded", "Excluded"),
                ],
                default="Unknown",
                max_length=30,
            ),
        ),
    ]
