# Generated by Django 4.2.11 on 2024-03-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0026_remove_participant_exlusion_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("Enrolled", "Enrolled"),
                    ("Screened", "Screened"),
                    ("Excluded", "Excluded"),
                ],
                default="Enrolled",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="exclusion_reason",
            field=models.CharField(
                choices=[
                    ("Withdrawn Consent", "Withdrawn"),
                    ("Ineligible", "Ineligible"),
                    ("Other", "Other"),
                ],
                default="Withdrawn Consent",
                max_length=20,
            ),
        ),
    ]
