# Generated by Django 4.2.11 on 2024-03-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0027_alter_participant_enrollment_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicationrecord",
            old_name="participant_id",
            new_name="participant_name",
        ),
        migrations.AlterField(
            model_name="adverse_events",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Mild", "Mild"),
                    ("Moderate", "Moderate"),
                    ("Severe", "Severe"),
                ],
                default="Mild",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adverse_events",
            name="severity",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                max_length=20,
            ),
        ),
    ]
